export const TEXT = {
  standard: {
    levelTransitionLoading: 'ROUTE WIRD GELADEN',
    mapEventBootAnnouncement: 'Ein besonderes Ereignis wurde auf der Passau-Karte erkannt.',
    mapEventBootKicker: 'UNERWARTETES KARTENEREIGNIS',
    mapEventBootTitle: 'Sonderstelle F-60 fährt hoch …',
    mapEventBootWait: 'BITTE DEN VORGANG NICHT STÖREN',
    mapEventBootLineOne: 'Passau-Netz wird synchronisiert',
    mapEventBootLineTwo: '9 von 9 Orten amtlich bestätigt',
    mapEventBootLineThree: 'Gutti-Archiv vollständig geprüft',
    mapEventBootLineFour: 'Versiegelte Sonderfreigabe gefunden',
    concertUnlockedAnnouncement: 'Das Konzert deiner Wahl ist jetzt auf der Karte freigeschaltet.',
    eyebrow: 'EIN KLEINES ABENTEUER AUS PASSAU',
    scoreLabel: 'PUNKTE', bestLabel: 'BESTE RUNDE', roundLabel: 'LEVEL', livesLabel: 'LEINEN',
    globalProgressLabel: 'PASSAU-FORTSCHRITT',
    mapKicker: 'DEINE GASSI-KARTE', mapTitle: 'Wo geht es heute hin?',
    mapCopy: 'Wähle einen Ort in Passau. Die Abstände der Punkte sind geografisch skaliert.',
    mapStart: 'LEVEL STARTEN →', mapResume: 'WEITERGASSI →', mapButton: 'PASSAU-KARTE',
    cutsceneSkip: 'ÜBERSPRINGEN →',
    settingsLabel: 'EINSTELLUNGEN', settingsKicker: 'SPIEL & DARSTELLUNG', settingsTitle: 'Gassi-Zentrale',
    settingsMapContext: 'PASSAU-KARTE', settingsGameContext: 'LAUFENDE RUNDE',
    settingsMapContextCopy: 'Dauerhafte Vorgaben und Spielstand verwalten.',
    settingsGameContextCopy: 'Die aktuelle Runde steuern, ohne den Spielfluss zu verlieren.',
    settingsComfortLabel: 'KOMFORT', settingsRoundLabel: 'RUNDE', settingsDataLabel: 'SPIELSTAND',
    settingsSystemLabel: 'SYSTEM', settingsCloseLabel: 'Einstellungen schließen',
    reducedMotionOn: '◌  WENIGER BEWEGUNG AN', reducedMotionOff: '◉  WENIGER BEWEGUNG AUS',
    reducedMotionCopy: 'Reduziert Übergänge, Kartenbewegung und Konfetti. Die Spielsteuerung bleibt direkt.',
    menuLabel: 'MENÜ', levelIntroKicker: 'KURZ DIE LEINE SORTIEREN', levelIntroTitle: '{place}',
    levelIntroCopy: '{description}', controlIntroHint: 'Wische in die gewünschte Richtung. Lola übernimmt den Richtungswechsel sofort.',
    controlMenuHint: 'Mobil wischen, am Desktop Pfeiltasten oder WASD verwenden.',
    difficultyLabel: 'SCHWIERIGKEIT', difficultyEasy: 'Spaziergang', difficultyNormal: 'Gassirunde', difficultyHard: 'Abenteuer',
    easyHint: '2 Katzen · 5 Leinen · 70 Guttis · lange Schnüffel-Power',
    normalHint: '3 Katzen · 3 Leinen · 110 Guttis · ausgewogenes Tempo',
    hardHint: '3 schnelle Katzen · 2 Leinen · 160 Guttis',
    treatProgressLabel: 'GUTTIS GESAMMELT',
    languageLabel: 'SPRACHE', standardButton: 'Schönes Deutsch', dialectButton: 'Niederbairisch*',
    languageJoke: '* Amtlich keine eigene Sprache – aber versuchen Sie das einmal einem Niederbayern zu erklären.',
    flavourQuote: '„Nur noch eine kleine Runde.“', flavourByline: '— Franz, seit 45 Minuten',
    keyHint: 'PFEILTASTEN / WASD · P ZUM PAUSIEREN', mobileHint: 'WISCHEN LENKT SOFORT',
    mobileBackMap: 'PASSAU-KARTE', enterFullscreenLabel: 'Vollbild aktivieren', exitFullscreenLabel: 'Vollbild verlassen',
    routeOne: 'START', routeTwo: 'GUTTIS', routeThree: 'ZIEL', secretsLabel: 'PASSAU-GEHEIMNISSE',
    guideLabel: 'GASSI-GUIDE', treatTitle: 'Gutti', treatCopy: '+10 Punkte',
    powerTitle: 'Schnüffel-Power', powerCopy: 'Die Katzen suchen das Weite',
    catTitle: 'Nachbarskatzen', catCopy: 'Lieber Abstand halten', controlsLabel: 'STEUERUNG', orLabel: 'oder',
    footerPlace: 'PASSAU · STADT & FLÜSSE', footerTagline: 'PIXEL FÜR PIXEL DURCH DIE NACHT',
    saveSuccess: 'IM BROWSER GESPEICHERT', saveBlocked: 'SPEICHER IST GESPERRT',
    pause: 'Ⅱ  PAUSE', continue: '▶  WEITER', soundOn: '♪  TON AN', soundOff: '♪  TON AUS',
    startKicker: 'DIE ABENDRUNDE BEGINNT', startTitle: 'Los geht’s, Franz!',
    startCopy: 'Sammle alle Guttis ein, halte Abstand zu den Nachbarskatzen und bringe Lola sicher ans Ziel.',
    startButton: 'AUF GEHT’S →', resumeKicker: 'DEINE RUNDE IST NOCH DA', resumeTitle: 'Willkommen zurück, Franz!',
    resumeCopy: 'Level {level}, {score} Punkte und {lives} {leash} wurden sicher im Browser gespeichert.',
    resumeButton: 'WEITERGASSI →', leashOne: 'Leine', leashMany: 'Leinen',
    pauseKicker: 'EINE KLEINE VERSCHNAUFPAUSE', pauseTitle: 'Warte kurz, Lola!',
    pauseCopy: 'Die Runde ist pausiert. Franz bindet sich nur schnell einen Schuh.', pauseButton: 'WEITER GEHT’S →',
    winKicker: 'ALLE GUTTIS SIND EINGESAMMELT', winTitle: 'Sauber, das war’s!',
    winCopy: 'Lola ist zufrieden und Franz ein wenig müde. Dieser Ort ist jetzt auf der Passau-Karte abgehakt.',
    winButton: 'ZUR PASSAU-KARTE →', overKicker: 'DIE KATZEN WAREN HEUTE SCHNELLER', overTitle: 'Jetzt geht es heim.',
    overCopy: 'Franz und Lola haben {score} Punkte gesammelt. Morgen versuchen sie es wieder.', overButton: 'NOCH EINMAL →',
    playAnnouncement: 'Auf geht es mit Franz und Lola', powerAnnouncement: 'Schnüffel-Power! Die Katzen suchen das Weite',
    eggIlz: 'Donnerwetter, ein Eisvogel an der Ilz!', eggPark: 'Lola hat ihren Lieblingsplatz gefunden!',
    eggBell: 'Bim bam! Die Passauer Glocken läuten nur für euch.', secretFound: 'Geheimnis entdeckt: {message}',
    missionPrefix: 'HEUTIGE RUNDE', mapSelected: 'AUSGEWÄHLT', mapCompleted: 'GESCHAFFT',
    mapStatsTreats: 'GUTTIS', mapStatsAttempts: 'VERSUCHE', mapStatsScore: 'BESTE PUNKTE',
    mapStatsStatus: 'STATUS', mapStatsOpen: 'NOCH OFFEN', mapStatsActive: 'AKTIVE RUNDE',
    mapStatsDone: 'GESCHAFFT', mapDetailsClose: 'Ortsdetails schließen',
    mapAggregateLevels: 'LEVEL ABGESCHLOSSEN', mapAggregateTreats: 'GUTTIS GEFUNDEN',
    levelScoreLabel: 'LEVEL-PUNKTE', levelRemainingLabel: 'NOCH OFFEN',
    finaleKicker: '100% PASSAU', finaleTitle: 'Ganz Passau ist geschafft!',
    finaleCopy: 'Franz und Lola haben alle neun Gassi-Orte erkundet. Jedes Gutti, jeder Umweg und jede Leine haben sich gelohnt.',
    finaleButton: 'ZUR EHRENRUNDE →',
    endgameOneButton: 'AKTE ÖFFNEN →',
    endgameTwoKicker: 'AMTLICHE ABSCHLUSSPRÜFUNG', endgameTwoTitle: 'Vorgang F-60 genehmigt!',
    endgameTwoCopy: 'Neun Orte, sämtliche Guttis und eine bemerkenswerte Menge Ausdauer: Die Sonderstelle bestätigt den vollständigen Abschluss der Passauer Ehrenrunde.',
    endgameTwoButton: 'BELOHNUNG ENTSIEGELN →',
    endgameThreeKicker: 'PERSÖNLICHE SONDERFREIGABE', endgameThreeTitle: 'Franz, dein Konzert wartet!',
    endgameThreeCopy: 'Du hast ein Konzert deiner Wahl freigeschaltet. Such dir aus, wen du live erleben möchtest – dieser Abend gehört dir.',
    endgameThreeButton: 'FREIGABE MITNEHMEN →', concertMapBadge: 'KONZERT FREIGESCHALTET',
    newGameButton: '↺ NEUER SPIELSTAND', newGameKicker: 'WIRKLICH NEU ANFANGEN?',
    newGameTitle: 'Eine neue Gassi-Karte?',
    newGameCopy: 'Punkte, Orts-Häkchen und Geheimnisse werden gelöscht. Sprache, Ton, Schwierigkeit und Bewegungskomfort bleiben erhalten.',
    newGameConfirm: 'JA, NEU STARTEN', cancelButton: 'ABBRECHEN',
    deleteBrowserDataButton: '⚠ ALLE BROWSERDATEN LÖSCHEN',
    deleteDataKicker: 'LETZTE SICHERHEITSABFRAGE', deleteDataTitle: 'Die komplette Akte vernichten?',
    deleteDataCopy: 'Der gesamte Spielstand dieses Spiels wird aus dem Browser gelöscht – einschließlich Leveln, Punkten, Einstellungen und Einweisung. Danach beginnt Vorgang 60 wieder ganz von vorn. Das lässt sich nicht rückgängig machen.',
    deleteDataConfirm: 'JA, ALLES ENDGÜLTIG LÖSCHEN',
    deleteDataErrorKicker: 'LÖSCHUNG BLOCKIERT', deleteDataErrorTitle: 'Die Akte klemmt im Schredder',
    deleteDataErrorCopy: 'Der Browser hat das Löschen verhindert. Bitte prüfe, ob Website-Daten oder privater Modus blockiert sind.',
    deleteDataErrorButton: 'ZURÜCK ZUM SPIEL',
  },
  dialect: {
    levelTransitionLoading: 'ROUTN WIRD GLADN',
    mapEventBootAnnouncement: 'Auf da Passau-Kartn is a ganz bsonders Ereignis auftaucht.',
    mapEventBootKicker: 'UNERWARTETS KARTNEREIGNIS',
    mapEventBootTitle: 'D’Sonderstell F-60 fahrt hoch …',
    mapEventBootWait: 'BITTE NED DREINPFUSCHN',
    mapEventBootLineOne: 'Passau-Netz werd zsammgschalten',
    mapEventBootLineTwo: '9 von 9 Platzerl amtlich bestätigt',
    mapEventBootLineThree: 'Gutti-Archiv vollständig geprüft',
    mapEventBootLineFour: 'Versiegelte Sonderfreigab gfundn',
    concertUnlockedAnnouncement: 'Dei Konzert nach Wahl is jetz auf da Kartn freigschoit.',
    eyebrow: 'A KLOANS ABENTEUER AUS PASSAU',
    scoreLabel: 'PUNKT', bestLabel: 'BESTE RUNDN', roundLabel: 'LEVEL', livesLabel: 'LEINEN',
    globalProgressLabel: 'PASSAU-FORTSCHRITT',
    mapKicker: 'DEI GASSI-KARTN', mapTitle: "Wo geh ma heit hi?",
    mapCopy: 'Suach da a Platzerl in Passau aus. De Abständ san geografisch skaliert.',
    mapStart: 'LEVEL STARTN →', mapResume: 'WEIDAGASSI →', mapButton: 'PASSAU-KARTN',
    cutsceneSkip: 'ÜBERSPRINGA →',
    settingsLabel: 'EINSTELLUNGEN', settingsKicker: 'SPIEL & ANSCHAUN', settingsTitle: 'Gassi-Zentraln',
    settingsMapContext: 'PASSAU-KARTN', settingsGameContext: 'LAUFENDE RUNDN',
    settingsMapContextCopy: 'Dauerhafte Vorgabn und Spielstand richtn.',
    settingsGameContextCopy: "D'aktuelle Rundn steiern, ohne dass da Gassi-Fluss abreißt.",
    settingsComfortLabel: 'KOMFORT', settingsRoundLabel: 'RUNDN', settingsDataLabel: 'SPIELSTAND',
    settingsSystemLabel: 'SYSTEM', settingsCloseLabel: 'Einstellungen zumacha',
    reducedMotionOn: '◌  WENIGER BEWEGUNG O', reducedMotionOff: '◉  WENIGER BEWEGUNG AUS',
    reducedMotionCopy: "Bremst Übergäng, Kartnbewegung und Konfetti. D'Steuerung bleibt glei direkt.",
    menuLabel: 'MENÜ', levelIntroKicker: 'KURZ D’LEIN SORTIERN', levelIntroTitle: '{place}',
    levelIntroCopy: '{description}', controlIntroHint: 'Wisch in de Richtung, wo’s hi geh soi. D’Lola draht glei mit.',
    controlMenuHint: 'Mobil wischn, am Rechner Pfeiltastn oder WASD nehma.',
    difficultyLabel: 'WIA HART?', difficultyEasy: 'Gmiatlich', difficultyNormal: 'Gassirundn', difficultyHard: 'Sakrisch',
    easyHint: '2 Katzn · 5 Leinen · 70 Guttis · lange Schnüffel-Power',
    normalHint: '3 Katzn · 3 Leinen · 110 Guttis · guads Tempo',
    hardHint: '3 sakrisch flinke Katzn · 2 Leinen · 160 Guttis',
    treatProgressLabel: 'GUTTIS EIGSAMMELT',
    languageLabel: 'SPRACH', standardButton: 'Schönes Deutsch', dialectButton: 'Niederbairisch*',
    languageJoke: "* Koa richtige Sprach – aber des sogn aa bloß Leit, de's ned vastehn.",
    flavourQuote: '„Bloß no a kloane Rundn.“', flavourByline: '— da Franz, seit 45 Minutn',
    keyHint: 'PFEILTASTN / WASD · P ZUM PAUSIEREN', mobileHint: 'WISCHN LENKT GLEI',
    mobileBackMap: 'ZUR PASSAU-KARTN', enterFullscreenLabel: 'Vollbild o', exitFullscreenLabel: 'Vollbild aus',
    routeOne: 'START', routeTwo: 'GUTTIS', routeThree: 'ZIEL', secretsLabel: 'PASSAU-GEHEIMNIS',
    guideLabel: 'GASSI-GUIDE', treatTitle: 'Gutti', treatCopy: '+10 Punkt',
    powerTitle: 'Schnüffel-Power', powerCopy: "D'Katzn gebn Fersngeld",
    catTitle: 'Nochbarskatzn', catCopy: 'Liaba Abstand hoidn', controlsLabel: 'STEUERUNG', orLabel: 'oda',
    footerPlace: 'PASSAU · STADT & FLIASS', footerTagline: "PIXEL FÜR PIXEL DURCH D'NACHT",
    saveSuccess: "IM BROWSER G'SPEICHERT", saveBlocked: 'SPEICHER IS GSPERRT',
    pause: 'Ⅱ  PAUSE', continue: '▶  WEIDA', soundOn: '♪  TON O', soundOff: '♪  TON AUS',
    startKicker: "D'ABENDRUNDN GEHT O", startTitle: "Pack ma's, Franz!",
    startCopy: "Sammel olle Guttis ei, hoid di von de Nochbarskatzn fern und bring d'Lola guad ans Ziel.",
    startButton: "AUF GEHT'S →", resumeKicker: 'DEI RUNDN IS NO DO', resumeTitle: 'Servus zruck, Franz!',
    resumeCopy: "Level {level}, {score} Punkt und {lives} {leash} san sauber im Browser g'speichert.",
    resumeButton: 'WEIDAGASSI →', leashOne: 'Leine', leashMany: 'Leinen',
    pauseKicker: 'A KLOANE VERSCHNAUFPAUSN', pauseTitle: 'Wart amoi, Lola!',
    pauseCopy: "D'Rundn is pausiert. Da Franz bind't se bloß gschwind an Schuah.", pauseButton: "WEIDA GEHT'S →",
    winKicker: 'OLLE GUTTIS SAN EIGSAMMELT', winTitle: 'Sauba, des war’s!',
    winCopy: "D'Lola is zfriedn und da Franz a bisserl miad. Des Platzerl is auf da Passau-Kartn abghakt.",
    winButton: 'ZUR PASSAU-KARTN →', overKicker: 'DE KATZN WARN HEIT GSCHWINDER', overTitle: 'Jetz geht’s hoam.',
    overCopy: "Da Franz und d'Lola ham {score} Punkt eigsammelt. Moang pack ma's wieder.", overButton: 'NO AMOI →',
    playAnnouncement: "Auf geht's mit Franz und Lola", powerAnnouncement: "Schnüffel-Power! D'Katzn gebn Fersngeld",
    eggIlz: 'Sakradi, a Eisvogl an da Ilz!', eggPark: "Ja mei, d'Lola hod ihr Lieblingsplatzerl gfundn!",
    eggBell: "Bim bam! D'Passauer Glockn läutn bloß für eich.", secretFound: 'Geheimnis entdeckt: {message}',
    missionPrefix: 'HEITIGE RUNDN', mapSelected: 'AUSGWÄHLT', mapCompleted: 'GSCHAFFT',
    mapStatsTreats: 'GUTTIS', mapStatsAttempts: 'VERSUACH', mapStatsScore: 'BESTE PUNKT',
    mapStatsStatus: 'STATUS', mapStatsOpen: 'NO OFFN', mapStatsActive: 'AKTIVE RUNDN',
    mapStatsDone: 'GSCHAFFT', mapDetailsClose: 'Ortsdetails zumacha',
    mapAggregateLevels: 'LEVEL GSCHAFFT', mapAggregateTreats: 'GUTTIS GFUNDN',
    levelScoreLabel: 'LEVEL-PUNKT', levelRemainingLabel: 'NO OFFN',
    finaleKicker: '100% PASSAU', finaleTitle: 'Ganz Passau is abgassi’d!',
    finaleCopy: "Da Franz und d'Lola ham olle neun Gassi-Platzerl erkundet. Jeds Gutti, jeda Umweg und jede Leine ham se rentiert.",
    finaleButton: 'ZUR EHRENRUNDN →',
    endgameOneButton: 'AKT AUFMACHA →',
    endgameTwoKicker: 'AMTLICHE ABSCHLUSSPRÜAFUNG', endgameTwoTitle: 'Vorgang F-60 is genehmigt!',
    endgameTwoCopy: "Neun Platzerl, olle Guttis und a sakrische Ausdauer: D'Sonderstell bestätigt, dass de Passauer Ehrenrundn vollständig erledigt is.",
    endgameTwoButton: 'BELOHNUNG ENTSIEGELN →',
    endgameThreeKicker: 'PERSÖNLICHE SONDERFREIGAB', endgameThreeTitle: 'Franz, dei Konzert wart!',
    endgameThreeCopy: 'Du host a Konzert deiner Wahl freigschoit. Suach da aus, wenst live seng mogst – der Abend ghört dir.',
    endgameThreeButton: 'FREIGAB MITNEHMA →', concertMapBadge: 'KONZERT FREIGSCHOIT',
    newGameButton: '↺ NEIA SPIELSTAND', newGameKicker: 'WIRKLI VON VORN?',
    newGameTitle: 'A frische Gassi-Kartn?',
    newGameCopy: "Punkt, Orts-Hakerl und Geheimnis werdn glöscht. Sprach, Ton, Schwierigkeit und Bewegungskomfort bleibn wia's san.",
    newGameConfirm: 'JA, NEI STARTN', cancelButton: 'ABBRECHN',
    deleteBrowserDataButton: '⚠ OLLE BROWSERDATEN LÖSCHN',
    deleteDataKicker: 'LETZTE SICHERHEITSABFRAG', deleteDataTitle: 'De komplette Akt vernichtn?',
    deleteDataCopy: 'Da ganze Spielstand von dem Spiel werd ausm Browser glöscht – Level, Punkt, Einstellungen und Einweisung. Danach fangt Vorgang 60 wieder ganz von vorn o. Des ko ma ned rückgängig macha.',
    deleteDataConfirm: 'JA, OIS ENDGÜLTIG LÖSCHN',
    deleteDataErrorKicker: 'LÖSCHN BLOCKIERT', deleteDataErrorTitle: 'De Akt hängt im Schredder',
    deleteDataErrorCopy: 'Da Browser hod des Löschn verhindert. Bittsche prüaf, ob Website-Daten oder da private Modus blockiert san.',
    deleteDataErrorButton: 'ZRUCK ZUM SPIEL',
  },
};

export const ONBOARDING_GUIDE = {
  standard: [
    {
      kicker: 'SONDERAKTE F-60 · OFFENLEGUNG',
      title: 'Der Auftrag',
      copy: 'Der versiegelte Umschlag springt auf. Darin liegt eine Karte von Passau – und daneben wartet Lola bereits mit angelegter Leine. Zum 60. Geburtstag wurde eine ganz besondere Ehrenrunde genehmigt.',
      points: [
        'Neun Passauer Orte bilden das offizielle Einsatzgebiet.',
        'An jedem Ort müssen sämtliche Guttis ordnungsgemäß sichergestellt werden.',
        'Nachbarskatzen betrachten den Vorgang leider als ihre Zuständigkeit.',
      ],
      finePrint: 'Aktenvermerk: Lola führt die operative Leitung. Franz trägt die Leine und die Verantwortung.',
      next: 'ZUR BEDIENUNGSANWEISUNG →',
    },
    {
      kicker: 'DIENSTANWEISUNG · FORTBEWEGUNG',
      title: 'Lola gibt die Richtung vor',
      copy: 'Sobald sich die beiden in Bewegung setzen, genügt ein kurzer Richtungswunsch. Lola versteht ihn sofort – meistens sogar schneller als eine kommunale Dienststelle.',
      points: [
        'Desktop: Pfeiltasten oder W, A, S und D verwenden.',
        'Mobil: direkt auf dem Spielfeld in die gewünschte Richtung wischen.',
        'Richtungen dürfen schon kurz vor der nächsten Kreuzung vorgemerkt werden.',
      ],
      finePrint: 'P oder die Leertaste pausieren den Vorgang. Spontane Schuhbindepausen sind zulässig.',
      next: 'ZU DEN EINSATZMITTELN →',
    },
    {
      kicker: 'DIENSTANWEISUNG · EINSATZMITTEL',
      title: 'Was unterwegs wichtig wird',
      copy: 'Die Sonderstelle hat drei auffällig unbürokratische Hilfsmittel genehmigt. Das Zahnrad-Menü enthält außerdem Karte, Pause und Ton – falls die Lage eine geordnete Unterbrechung verlangt.',
      points: [
        'Gelbe Guttis zählen zum Auftrag und müssen vollständig eingesammelt werden.',
        'Die große Pfote aktiviert Schnüffel-Power und vertreibt Katzen vorübergehend.',
        'Randpfeile zeigen Katzen an, die außerhalb des sichtbaren Bereichs lauern.',
      ],
      finePrint: 'Damit ist die Einweisung abgeschlossen. Der eigentliche Vorgang beginnt auf der Passau-Karte.',
      finish: 'VORGANG 60 STARTEN →',
    },
  ],
  dialect: [
    {
      kicker: 'SONDERAKT F-60 · JETZT WERD AUFGMACHT',
      title: 'Da Auftrag',
      copy: "Da versiegelte Umschlag springt auf. Drin liegt a Kartn von Passau – und daneben wart d'Lola scho mit da Lein. Zum 60er is a ganz bsondere Ehrenrundn genehmigt worn.",
      points: [
        'Neun Passauer Platzerl san des amtliche Einsatzgebiet.',
        'An jedem Platzerl miassn olle Guttis sauber sichergstellt werdn.',
        "De Nochbarskatzn hoitn des leider aa für eahna Zuständigkeit.",
      ],
      finePrint: "Aktenvermerk: D'Lola hod d'Einsatzleitung. Da Franz hod d'Lein und d'Verantwortung.",
      next: 'ZUR BEDIENUNGSANWEISUNG →',
    },
    {
      kicker: 'DIENSTANWEISUNG · FORTBEWEGUNG',
      title: "D'Lola gibt d'Richtung vor",
      copy: "Sobald de zwoa unterwegs san, reicht a kurzer Richtungswunsch. D'Lola vasteht'n sofort – meistens schneller ois a kommunale Dienststell.",
      points: [
        'Am Rechner: Pfeiltastn oder W, A, S und D nehma.',
        'Mobil: direkt aufm Spielfeld in de gewünschte Richtung wischn.',
        'D Richtung ko scho kurz vor da nächsten Kreuzung vorgemerkt werdn.',
      ],
      finePrint: 'P oder d Leertastn pausiern den Vorgang. Schuahbindn is ausdrücklich erlaubt.',
      next: 'ZU DE EINSATZMITTEL →',
    },
    {
      kicker: 'DIENSTANWEISUNG · EINSATZMITTEL',
      title: 'Wos unterwegs wichtig werd',
      copy: 'De Sonderstell hod drei erstaunlich unbürokratische Hilfsmittel genehmigt. Im Zahnrad-Menü san außerdem Kartn, Pause und Ton – falls d Lage a gscheide Unterbrechung braucht.',
      points: [
        'De gelbn Guttis ghern zum Auftrag und miassn olle eigsammelt werdn.',
        'De große Pfotn aktiviert d Schnüffel-Power und vertreibt Katzn für a Zeitl.',
        'Randpfeile zoagn Katzn, de grad außerhalb vom sichtbaren Bereich lauern.',
      ],
      finePrint: 'Damit war d Einweisung. Da eigentliche Vorgang fangt auf da Passau-Kartn o.',
      finish: 'JETZT PACK MA VORGANG 60 →',
    },
  ],
};
